algorithms_explained/algo_explained/urls.py
from django.urls import path

from . import views

app_name = "algorithms"
urlpatterns = [
        path("", views.blog_index, name="blog_index"),
        path("<int:pk>/", views.blog_detail, name='blog_detail'),
        path("<category>/", views.blog_category, name='blog_category'),
]

algorithms_explained/users/urls.py
from django.urls import path

from algorithms_explained.users.views import (
    user_redirect_view,
    user_update_view,
    user_detail_view,
)

app_name = "users"
urlpatterns = [
    path("~redirect/", view=user_redirect_view, name="redirect"),
    path("~update/", view=user_update_view, name="update"),
    path("<str:username>/", view=user_detail_view, name="detail"),
]

config/urls.py
from django.conf import settings
from django.urls import include, path
from django.conf.urls.static import static
from django.contrib import admin
from django.views.generic import TemplateView
from django.views import defaults as default_views

urlpatterns = [
    # path("", TemplateView.as_view(template_name="pages/home.html"), name="home"),
    # path(
        # "about/", TemplateView.as_view(template_name="pages/about.html"), name="about"
    # ),
    # Django Admin, use {% url 'admin:index' %}
    path(settings.ADMIN_URL, admin.site.urls),
    # User management
    path("users/", include("algorithms_explained.users.urls", namespace="users")),
    path("accounts/", include("allauth.urls")),
    # Your stuff: custom urls includes go here
    path("", include("algorithms_explained.algo_explained.urls", namespace = "algorithms")),

] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    # This allows the error pages to be debugged during development, just visit
    # these url in browser to see how these error pages look like.
    urlpatterns += [
        path(
            "400/",
            default_views.bad_request,
            kwargs={"exception": Exception("Bad Request!")},
        ),
        path(
            "403/",
            default_views.permission_denied,
            kwargs={"exception": Exception("Permission Denied")},
        ),
        path(
            "404/",
            default_views.page_not_found,
            kwargs={"exception": Exception("Page not Found")},
        ),
        path("500/", default_views.server_error),
    ]
    if "debug_toolbar" in settings.INSTALLED_APPS:
        import debug_toolbar

        urlpatterns = [path("__debug__/", include(debug_toolbar.urls))] + urlpatterns

algorithms_explained/algo_explained/models.py
from django.db import models
from django.db.models import CharField

# Create your models here.
class Category(models.Model):
    name            = models.CharField(max_length = 20)

    def __str__(self):
        return self.name

class Post(models.Model):
    title           = models.CharField(max_length = 255)
    body            = models.TextField()
    created_on      = models.DateTimeField(auto_now_add = True)
    last_modified   = models.DateTimeField(auto_now = True)
    categories      = models.ManyToManyField('Category', related_name = "posts")

    def __str__(self):
        return self.title

class Comment(models.Model):
    author          = models.CharField(max_length = 60)
    body            = models.TextField()
    created_on      = models.DateTimeField(auto_now_add=True)
    post            = models.ForeignKey("Post", on_delete = models.CASCADE)

algorithms_explained/users/models.py
from django.contrib.auth.models import AbstractUser
from django.db.models import CharField
from django.urls import reverse
from django.utils.translation import ugettext_lazy as _


class User(AbstractUser):

    # First Name and Last Name do not cover name patterns
    # around the globe.
    name = CharField(_("Name of User"), blank=True, max_length=255)

    def get_absolute_url(self):
        return reverse("users:detail", kwargs={"username": self.username})

algorithms_explained/algo_explained/forms.py
from django import forms

class CommentForm(forms.Form):
    author = forms.CharField(
        max_length=60,
        widget=forms.TextInput(attrs={
            "class": "form-control",
            "placeholder": "Your Name"
        })
    )
    body = forms.CharField(widget=forms.Textarea(
        attrs={
            "class": "form-control",
            "placeholder": "Leave a comment!"
        })
    )

algorithms_explained/users/forms.py
from django.contrib.auth import get_user_model, forms
from django.core.exceptions import ValidationError
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserChangeForm(forms.UserChangeForm):
    class Meta(forms.UserChangeForm.Meta):
        model = User


class UserCreationForm(forms.UserCreationForm):

    error_message = forms.UserCreationForm.error_messages.update(
        {"duplicate_username": _("This username has already been taken.")}
    )

    class Meta(forms.UserCreationForm.Meta):
        model = User

    def clean_username(self):
        username = self.cleaned_data["username"]

        try:
            User.objects.get(username=username)
        except User.DoesNotExist:
            return username

        raise ValidationError(self.error_messages["duplicate_username"])

algorithms_explained/algo_explained/views.py
from django.shortcuts import render
from algorithms_explained.algo_explained.models import Post, Comment
from algorithms_explained.algo_explained.forms import CommentForm

#Do the class based view instead of function based view

#blog_index will display a list of all your posts.
def blog_index(request):
    posts = Post.objects.all().order_by('-created_on')
    context = {
        "posts" : posts
    }
    return render(request, "algo_explained/blog_index.html", context)

def blog_category(request, category):
    posts = Post.objects.filter(categories__name__contains=category).order_by('-created_on')
    context = {
        "category": category,
        "posts": posts
        }
    return render(request, "algo_explained/blog_category.html", context)


def blog_detail(request, pk):
    post = Post.objects.get(pk = pk)
    comments = Comment.objects.filter(post=post)

    form = CommentForm()
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = Comment(
                author = form.cleaned_data["author"],
                body   = form.cleaned_data["body"],
                post   = post,
            )
            comment.save()
            form = CommentForm()

    context = {
        "post": post,
        "comments": comments,
        "form": form
      }
    return render(request, "algo_explained/blog_detail.html", context)

algorithms_explained/users/views.py
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse
from django.views.generic import DetailView, RedirectView, UpdateView
from django.contrib import messages
from django.utils.translation import ugettext_lazy as _

User = get_user_model()


class UserDetailView(LoginRequiredMixin, DetailView):

    model = User
    slug_field = "username"
    slug_url_kwarg = "username"


user_detail_view = UserDetailView.as_view()


class UserUpdateView(LoginRequiredMixin, UpdateView):

    model = User
    fields = ["name"]

    def get_success_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})

    def get_object(self):
        return User.objects.get(username=self.request.user.username)

    def form_valid(self, form):
        messages.add_message(
            self.request, messages.INFO, _("Infos successfully updated")
        )
        return super().form_valid(form)


user_update_view = UserUpdateView.as_view()


class UserRedirectView(LoginRequiredMixin, RedirectView):

    permanent = False

    def get_redirect_url(self):
        return reverse("users:detail", kwargs={"username": self.request.user.username})


user_redirect_view = UserRedirectView.as_view()

algorithms_explained/templates/algo_explained/blog_category.html
{% extends "base.html" %}
{% block content %}
<!-- <div class="col-md-8 offset-md-2"> -->
    <h1> Showing Post related to:  {{ category | title }}</h1>
    <hr>
    <div class = "row">
    {% for post in posts %}
        <div class = "col-md-6">
          <div class = "card mb-3">
            <div class = "card-body">
              <h3 class = "card-title">{{ post.title | slice:":70" }}</h3>
        <small>
            {{ post.created_on.date }} |&nbsp;
            Tags:&nbsp;
            {% for category in post.categories.all %}
            <a href="{% url 'algorithms:blog_category' category.name %}">
                {{ category.name }}
            </a>&nbsp;
            {% endfor %}
        </small>
        <p class = "card-text">{{ post.body | slice:":100" }}...</p>
          <a href = "{% url 'algorithms:blog_detail' post.pk %}"
            class = "btn btn-outline-success">
              Read More
          </a>
        </div>
      </div>
    </div>

    {% endfor %}
</div>
{% endblock %}

algorithms_explained/templates/algo_explained/blog_detail.html
{% extends "base.html" %}
{% block content %}
<div class="col-md-8 offset-md-2">
    <h1>{{ post.title }}</h1>
    <small>
        Posted on: {{ post.created_on.date }} |&nbsp;
        Tags:&nbsp;
        {% for category in post.categories.all %}
        <a href="{% url 'algorithms:blog_category' category.name %}">
            {{ category.name }}
        </a>&nbsp;
        {% endfor %}
    </small>
    <p>{{ post.body | linebreaks }}</p>
    <h4>Leave a comment:</h4>
    <form action="/{{ post.pk }}/" method="post">
        {% csrf_token %}
        <div class="form-group">
            {{ form.author }}
        </div>
        <div class="form-group">
            {{ form.body }}
        </div>
        <button type="submit" class="btn btn-outline-primary">Submit</button>
    </form>
    <hr>
    <h3>Comments:</h3>
    {% for comment in comments %}
    <p>
        On {{comment.created_on.date }}&nbsp;
        <b>{{ comment.author }}</b> Says:
    </p>
    <p>{{ comment.body }}</p>
    <hr>
    {% endfor %}
</div>
{% endblock content %}

algorithms_explained/templates/algo_explained/blog_index.html
{% extends "base.html" %}
{% block content %}

<!-- <div class="col-md-8 offset-md-2"> -->
<center><h1>Blog Index</h1></center>
<div class = "row">
  {% for post in posts %}
      <div class = "col-md-6">
        <div class = "card mb-3">
          <div class = "card-body">
            <!-- <h2 class = "card-title"><a href="{% url 'algorithms:blog_detail' post.pk%}">{{ post.title }}</a></h2> -->
            <h3 class = "card-title">{{ post.title | slice:":73" }}</h3>
            <small>
            || Posted on: {{ post.created_on.date }} ||&nbsp; Tags:
              <!-- <p class = "card-title"> Categories:&nbsp; </p> -->
              {% for category in post.categories.all %}
              <a href="{% url 'algorithms:blog_category' category.name %}">
                {{ category.name }}
              </a>&nbsp;||
              {% endfor %}
              <br>
              <br>
              </small>
              <p class = "card-text">{{ post.body | slice:":100" }}...</p>
              <a href="{% url 'algorithms:blog_detail' post.pk %}"
                 class="btn btn-outline-success">
                  Read More
              </a>
              </div>
          </div>
      </div>
    {% endfor %}
</div>
{% endblock content %}

algorithms_explained/templates/base.html
{% load static i18n compress%}<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>{% block title %}algorithms_explained{% endblock title %}</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">

    <!-- HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/html5shiv/3.7.3/html5shiv.min.js"></script>
    <![endif]-->

    <link rel="icon" href="{% static 'images/favicons/books.ico' %}">

    {% block css %}
    <style type = "text/css">
      body { background: #DDDDDD !important; }
      </style>

    <!-- Latest compiled and minified Bootstrap CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">


    <!-- Your stuff: Third-party CSS libraries go here -->
    {% compress css %}
    <!-- This file stores project-specific CSS -->

    <link href="{% static 'css/project.css' %}" rel="stylesheet">
    <link href="{% static 'css/project.css' %}" rel="stylesheet">

    {% endcompress %}
    {% endblock %}

  </head>

  <body>

    <div class="mb-1">
      <nav class="navbar navbar-expand-md navbar-light bg-primary">
        <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        <a class="navbar-brand" href="{% url 'algorithms:blog_index' %}">Explain Algorithms </a>
        <a class="navbar-brand" href="{% url 'algorithms:blog_index' %}">All Posts </a>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
            </li>
            <li class="nav-item">
            </li>
          </ul>
          <form class="form-inline my-2 my-lg-0">
              <input class="form-control mr-sm-2" type="search" placeholder="Type a tag name" aria-label="Search">
              <button class="btn btn-success my-2 my-sm-1 mr-sm-4" type="submit">Search By Tag</button>
            </form>
        </div>
      </nav>
    </div>

    <div class="container">

      {% if messages %}
          {% for message in messages %}
              <div class="alert {% if message.tags %}alert-{{ message.tags }}{% endif %}">{{ message }}<button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button></div>
          {% endfor %}
      {% endif %}

      {% block content %}
        <p>Use this document as a way to quick start any new project.</p>
      {% endblock content %}

    </div> <!-- /container -->

    {% block modal %}{% endblock modal %}

    <!-- Le javascript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    {% block javascript %}

      <!-- Bootstrap JS and its dependencies-->
      <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
      <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
      <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>

      <!-- Your stuff: Third-party javascript libraries go here -->


      <!-- place project specific Javascript in this file -->
      {% compress js %}
      <script src="{% static 'js/project.js' %}"></script>
      {% endcompress %}

    {% endblock javascript %}
  </body>
</html>

algorithms_explained/templates/pages/about.html
{% extends "base.html" %}

algorithms_explained/templates/pages/home.html
{% extends "base.html" %}

algorithms_explained/templates/users/user_detail.html
{% extends "base.html" %}
{% load static %}

{% block title %}User: {{ object.username }}{% endblock %}

{% block content %}
<div class="container">

  <div class="row">
    <div class="col-sm-12">

      <h2>{{ object.username }}</h2>
      {% if object.name %}
        <p>{{ object.name }}</p>
      {% endif %}
    </div>
  </div>

{% if object == request.user %}
<!-- Action buttons -->
<div class="row">

  <div class="col-sm-12">
    <a class="btn btn-primary" href="{% url 'users:update' %}" role="button">My Info</a>
    <a class="btn btn-primary" href="{% url 'account_email' %}" role="button">E-Mail</a>
    <!-- Your Stuff: Custom user template urls -->
  </div>

</div>
<!-- End Action buttons -->
{% endif %}


</div>
{% endblock content %}

algorithms_explained/templates/users/user_form.html
{% extends "base.html" %}
{% load crispy_forms_tags %}

{% block title %}{{ user.username }}{% endblock %}

{% block content %}
  <h1>{{ user.username }}</h1>
  <form class="form-horizontal" method="post" action="{% url 'users:update' %}">
    {% csrf_token %}
    {{ form|crispy }}
    <div class="control-group">
      <div class="controls">
        <button type="submit" class="btn btn-primary">Update</button>
      </div>
    </div>
  </form>
{% endblock %}